# Generated by Django 4.1.3 on 2023-01-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fiscalyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liter', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('fiscalyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fiscalyear')),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fueltype')),
                ('patrolpump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.petrolpump')),
            ],
        ),
    ]
