# Generated by Django 4.1.3 on 2023-01-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fuelexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workplace',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
